# Site settings
title: alan-conway.github.io
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alan-conway.github.io" # the base hostname & protocol for your site
# Build settings
future: true
permalink: none
markdown: kramdown
kramdown:
    input: GFM
